# Generated by Django 2.2.28 on 2023-04-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_submenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bjdjdj', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mndhej',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdjkd', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Nhuddi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcdjd', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Zadsfs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdhdd', models.BigIntegerField()),
            ],
        ),
    ]
